# Generated by Django 5.1.6 on 2025-02-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_badge_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
