# Generated by Django 5.1.6 on 2025-02-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_description_de_task_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title_fr',
        ),
    ]
