# Generated by Django 5.1.6 on 2025-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
